name: Build package
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build HibernateGenerator/HibernateGenerator.csproj -c:Release
      # - run: |
      #     ls -la HibernateGenerator/bin/Release/net8.0/HibernateGenerator.dll
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: HibernateGenerator/bin/Release/net8.0/HibernateGenerator.dll
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: HibernateGenerator/bin/Release/net8.0/HibernateGenerator.dll
